using Avalonia.Layout;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using System;
using System.Collections;
using System.Collections.ObjectModel;
using System.ComponentModel;
using SukiUI.Controls;
#pragma warning disable CS0657 // Not a valid attribute location for this declaration

namespace SukiUI.Demo.Features.ControlsLibrary;

/// <summary>
/// A demonstration of a Form ViewModel.
/// The `property:` part is to target the property generated by CommunityToolkits sourcegen.
/// </summary>
public partial class FormViewModel : ObservableObject, IPropertyGridOptionSource
{
    [ObservableProperty] [property: Category("Category 1"), DisplayName("Nullable name")]
    private string? _nullableName;

    [ObservableProperty] [property: Category("Category 1"), DisplayName("Nullable description")]
    private string? _nullableDescription;

    [ObservableProperty] [property: Category("Category 1"), DisplayName("Nullable boolean")]
    private bool? _nullableBoolean;

    [ObservableProperty] [property: Category("Category 1"), DisplayName("Nullable dateTime")]
    private DateTime? _nullableDateTime;

    [ObservableProperty] [property: Category("Category 1"), DisplayName("Nullable dateTimeOffset")]
    private DateTimeOffset? _nullableDateTimeOffset;

    [ObservableProperty] [property: Category("Nullable numbers"), DisplayName("Nullable integer")]
    private int? _nullableInteger;

    [ObservableProperty] [property: Category("Nullable numbers"), DisplayName("Nullable long")]
    private long? _nullableLong;

    [ObservableProperty] [property: Category("Nullable numbers"), DisplayName("Nullable decimal")]
    private decimal? _nullableDecimal;

    [ObservableProperty] [property: Category("Nullable numbers"), DisplayName("Nullable float")]
    private float? _nullableFloat;

    [ObservableProperty] [property: Category("Nullable numbers"), DisplayName("Nullable double")]
    private double? _nullableDouble;

    [ObservableProperty] [property: Category("Category 2"), DisplayName("Name")]
    private string _name = string.Empty;

    [ObservableProperty] [property: Category("Category 2"), DisplayName("Description")]
    private string _description = string.Empty;

    [ObservableProperty] [property: Category("Numbers"), DisplayName("Integer")]
    private int _integer;

    [ObservableProperty] [property: Category("Numbers"), DisplayName("Decimal")]
    private decimal _decimal;

    [ObservableProperty] [property: Category("Category 2"), DisplayName("Boolean")]
    private bool _boolean;

    [ObservableProperty] [property: Category("Category 2"), DisplayName("DateTime")]
    private DateTime _dateTime = DateTime.MinValue;

    [ObservableProperty] [property: Category("Category 2"), DisplayName("DateTimeOffset")]
    private DateTimeOffset _dateTimeOffset = DateTimeOffset.MinValue;

    [ObservableProperty] [property: Category("Category 2"), DisplayName("Child form")]
    private ChildFormViewModel _childForm = new ChildFormViewModel();

    [ObservableProperty] [property: Category("Category 2"), DisplayName("Orientation")]
    private Orientation _orientation;

    [ObservableProperty] [property: Category("Combo Values"), DisplayName("List of Values")]
    private string _status = "Draft";

    /// <summary>
    /// Values offered for <see cref="Status"/>. Kept off the public surface so the grid never
    /// mistakes them for a property of its own.
    /// </summary>
    private ObservableCollection<string> StatusOptions { get; set; } = new(StatusPool[..3]);

    private static readonly string[] StatusPool =
        ["Draft", "In progress", "Complete", "Blocked", "In review", "Cancelled"];

    public IEnumerable? GetOptions(string propertyName) => propertyName switch
    {
        nameof(Status) => StatusOptions,
        _ => null
    };

    /// <summary>
    /// Reorders the existing collection. The editor watches that collection directly, so the new
    /// order appears without the ViewModel having to notify anything.
    /// </summary>
    [RelayCommand]
    [property: PropertyGridIgnore]
    private void ShuffleStatusOptions()
    {
        var shuffled = StatusOptions.OrderBy(_ => Random.Shared.Next()).ToList();

        StatusOptions.Clear();
        
        foreach (var option in shuffled)
        {
            StatusOptions.Add(option);
        }
    }

    /// <summary>
    /// Swaps in a brand new collection of a random size. That is picked up through
    /// <see cref="INotifyPropertyChanged"/> rather than through the collection itself.
    /// </summary>
    [RelayCommand]
    [property: PropertyGridIgnore]
    private void ReplaceStatusOptions()
    {
        StatusOptions = new ObservableCollection<string>(
            StatusPool.OrderBy(_ => Random.Shared.Next()).Take(Random.Shared.Next(2, StatusPool.Length + 1)));
        OnPropertyChanged(nameof(StatusOptions));

        // Keep the selection valid now that the old values may be gone.
        if (!StatusOptions.Contains(Status))
        {
            Status = StatusOptions[0];
        }
    }
}

public partial class ChildFormViewModel : ObservableObject
{
    [ObservableProperty] [property: Category("Text"), DisplayName("Name")]
    private string _name = string.Empty;

    [ObservableProperty] [property: Category("Text"), DisplayName("Description")]
    private string _description = string.Empty;

    [ObservableProperty] [property: Category("Numbers"), DisplayName("Integer")]
    private int _integer;

    [ObservableProperty] [property: Category("Numbers"), DisplayName("Decimal")]
    private decimal _decimal;

    [ObservableProperty] [property: Category("Misc"), DisplayName("Boolean")]
    private bool _boolean;

    [ObservableProperty] [property: Category("Misc"), DisplayName("DateTimeOffset")]
    private DateTimeOffset _dateTimeOffset = DateTimeOffset.MinValue;
}

#pragma warning restore CS0657 // Not a valid attribute location for this declaration