<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <AvaloniaVersion>12.1.1</AvaloniaVersion>
    <DockVersion>12.1.0.1</DockVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.LinuxFramebuffer" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Simple" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Controls.DataGrid" Version="12.1.2" />
    <PackageVersion Include="Avalonia.Controls.ColorPicker" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageVersion Include="Dock.Avalonia" Version="$(DockVersion)" />
    <PackageVersion Include="Dock.Avalonia.Themes.Fluent" Version="$(DockVersion)" />
    <PackageVersion Include="Dock.Model" Version="$(DockVersion)" />
    <PackageVersion Include="Dock.Model.Avalonia" Version="$(DockVersion)" />
    <PackageVersion Include="Dock.Model.Mvvm" Version="$(DockVersion)" />
    <PackageVersion Include="Dock.Serializer.SystemTextJson" Version="$(DockVersion)" />
    <PackageVersion Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
    <PackageVersion Include="AvaloniaEdit.TextMate" Version="12.0.0" />
    <PackageVersion Include="Markdown.Avalonia" Version="12.0.0-a3" />
    <PackageVersion Include="Material.Icons.Avalonia" Version="3.0.2" />
    <PackageVersion Include="ShowMeTheXaml.Avalonia" Version="1.5.3" />
    <PackageVersion Include="ShowMeTheXaml.Avalonia.Generator" Version="1.5.3" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageVersion Include="System.Linq.Dynamic.Core" Version="1.7.3" />
    <PackageVersion Include="System.Text.Json" Version="10.0.5" />
  </ItemGroup>
</Project>
