<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <IsPackable>false</IsPackable>
    <Title>SukiUI Demo</Title>
    <Description>Interactive demonstration and showcase application for the SukiUI library suite.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.AvaloniaEdit" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="AvaloniaUI.DiagnosticsSupport" />
    <PackageReference Include="Avalonia.LinuxFramebuffer" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="AvaloniaEdit.TextMate" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Dock.Avalonia" />
    <PackageReference Include="Dock.Model" />
    <PackageReference Include="Dock.Model.Avalonia" />
    <PackageReference Include="Dock.Model.Mvvm" />
    <PackageReference Include="Dock.Serializer.SystemTextJson" />
    <PackageReference Include="Markdown.Avalonia" />
    <PackageReference Include="Material.Icons.Avalonia" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="ShowMeTheXaml.Avalonia" />
    <PackageReference Include="ShowMeTheXaml.Avalonia.Generator" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SukiUI.DataGrid\SukiUI.DataGrid.csproj" />
    <ProjectReference Include="..\SukiUI.Dock\SukiUI.Dock.csproj" />
    <ProjectReference Include="..\SukiUI\SukiUI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="..\Images\OIG.N5o-removebg-preview.png" Link="Assets\OIG.N5o-removebg-preview.png" />
    <AvaloniaResource Include="Assets\**\*.png" />
    <AvaloniaResource Include="Assets\**\*.jpg" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*.sksl" />
  </ItemGroup>

</Project>
